# Generated by Django 5.0.3 on 2024-04-03 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0002_lobby_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(related_name='lobby', to=settings.AUTH_USER_MODEL),
        ),
    ]
