# Generated by Django 5.0.3 on 2024-04-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0003_alter_lobby_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='game',
        ),
    ]
