# Generated by Django 5.0.3 on 2024-04-20 07:40

import superttt.types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0004_remove_lobby_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='gameType',
            field=models.IntegerField(default=None, verbose_name=superttt.types.GameType),
            preserve_default=False,
        ),
    ]
