# Generated by Django 5.0.3 on 2024-04-08 05:49

import django.contrib.postgres.fields
import django.db.models.deletion
import superttt.types
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameType', models.IntegerField(choices=[(0, 'Superttt')])),
                ('ended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuperTTT',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='superttt.game')),
                ('turn', models.IntegerField(verbose_name=superttt.types.SuperTTTPlayerSymbol)),
                ('hasEnded', models.BooleanField(default=False)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='-', max_length=1), size=9), size=9)),
            ],
            bases=('superttt.game',),
        ),
        migrations.CreateModel(
            name='SuperTTTPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.IntegerField(choices=[(0, 'Circle'), (1, 'Cross')])),
                ('hasWon', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superttt.superttt')),
            ],
        ),
    ]
