# Generated by Django 5.0.3 on 2024-04-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0004_remove_lobby_game'),
        ('superttt', '0002_remove_superttt_hasended'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lobby',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='lobbies.lobby'),
            preserve_default=False,
        ),
    ]
