# Generated by Django 5.0.3 on 2024-04-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superttt', '0004_alter_superttt_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertttplayer',
            name='symbol',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Circle'), (2, 'Cross')]),
        ),
    ]
