# Generated by Django 5.0.3 on 2024-04-21 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superttt', '0009_alter_superttt_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertttplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='superttt.superttt'),
        ),
    ]
