# Generated by Django 5.0.3 on 2024-04-21 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superttt', '0010_alter_supertttplayer_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supertttplayer',
            name='hasWon',
        ),
        migrations.AlterField(
            model_name='superttt',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'None'), (1, 'Circle'), (2, 'Cross'), (3, 'Nullplayer')]), size=10), size=9),
        ),
        migrations.AlterField(
            model_name='supertttplayer',
            name='symbol',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Circle'), (2, 'Cross'), (3, 'Nullplayer')]),
        ),
    ]
